org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version = 26.1.1
minecraft_version_supported = [26.1,26.1.1]
minecraft_version_lower = 1.21.11
minecraft_version_upper =

# File Name
minecraft_version_name = 26.1
archives_base_name = MoreCrafterVariants

# Mod Properties

mod_id=quad-lolmcrv
mod_name=More Crafter Variants
mod_name_short=More Crafter Variants
mod_license=CC-BY-NC-SA-4.0
mod_version=1.1.1
mod_group_id=de.pnku.mcrv
mod_description=Adding crafter variants to Minecraft

# Quad Properties
quad_version_id = suWFkmph
mct_version_id = XsN6Ellv